### ISSUE TITLE
Request: M3U files into the repository

### ISSUE THREAD

**Issue by lars18th** [localhosthack0r/kingofsat2satip#1]
Hi @localhosthack0r ,

I feel it will be good to upload the created M3U files to the repository. In this case, any user can download them at any time.

You agree?

**Comment by localhosthack0r** [comment]
Hi @lars18th 

thank you for your request!

As I think binaries or generated files should not be part of a source code repo, I will not do this.

Well, I can imagine to upload the M3Us as release. On the other hand, they can be genareted very easy and I think they have to be modified anyways to your individual setup regarding the server name/IP and your DiseqC setup. So they would not be ready to use after download, for everybody. At least manual search&replace needs to be done.

Another question, which lets me doubt is the copyright on the data, provided from the kingofsat.net website. So maybe it's better not to publish anything which replicates the data owned by kingofsat.

So all in all: No, I don't agree, sorry!

**Comment by lars18th** [comment]
Ok, I accept your opinion.

However, note this:
- A simple "search&replace" can be done with a `sed` command. So, I suggest to add to the project a simple shell script with this functionality.

Regards.

**Comment by localhosthack0r** [comment]
Feel free to create a PR!
