### ISSUE TITLE
Request: grab modulation type

### ISSUE THREAD

**Issue by stoli412** [localhosthack0r/kingofsat2satip#2]
Thank you for creating this fantastic script! It's working great except that my satip server requires the modulation type be set in the URL (&mtype=qpsk [or 8psk]) to be able to tune correctly. It defaults to qpsk if mtype is not specified, so it fails for any transponder using 8psk.

Would you be able to modify the python script to also extract the modulation parameters from the php file? I have little/no knowledge of python to modify it myself.

**Comment by iMiMx** [comment]
Quick hack, seems to do what's needed:

https://github.com/localhosthack0r/kingofsat2satip/pull/3

Examples:

```
rtsp://@10.x.x.xx/?src=1&freq=10818&pol=V&msys=DVBS&mtype=QPSK&sr=22000&pids=0,5400,5402,267,5400,5403
rtsp://@10.x.x.xx/?src=1&freq=10847&pol=V&msys=DVBS2&mtype=8PSK&sr=23000&pids=0,5400,5402,260,5400,5403
```

**Comment by iMiMx** [comment]
Just for completeness, simple perl command to convert from rtsp to http - might add an option to the script at some point, but the below does what's needed:

`perl -pi -e 's/rtsp\:\/\/\@/http\:\/\//g' allChannels.m3u`

**Comment by localhosthack0r** [comment]
Sorry, guys, I didn't look into github since a while.
Of course adding the modulation type makes sence. Thank you @iMiMx for the PR, I just merged it. :-)
